### ISSUE TITLE
null

### ISSUE THREAD

**Issue by mashazavolnyuk** [natashalysakova/DniproFuture#54]
чисто теоретически,как вы будете работать с такими данными,когда у вас есть пользователь с фамилией или именем - null?думаю здесь могут возникнуть проблемы

**Comment by natashalysakova** [comment]
Проблем не возникает - запись будет храниться с именем "null" (в кавычках), в то время как значение NULL - храниться без кавычек. Т.е. когда введенный пользователем нулл попадает из формы в модель, он преобразуется сразу в строку, а в строке он уже никак не может повлиять на работоспособность.
